# Kafka Bootstrap
spring.kafka.bootstrap-servers=localhost:9092

# Consumer settings (?????? ?? telemetry.sensors.v1)
spring.kafka.consumer.group-id=aggregator-group-test
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=ru.yandex.practicum.kafka.telemetry.aggregator.serialization.SensorEventDeserializer

# Producer settings (???????? ? telemetry.snapshots.v1)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=ru.yandex.practicum.kafka.telemetry.aggregator.serialization.AvroSerializer
# ???????????: ????? ?????? acks=all ??? ??????????
spring.kafka.producer.acks=all

# ??????
kafka.topic.sensors=telemetry.sensors.v1
kafka.topic.snapshots=telemetry.snapshots.v1

# ??????????? (??? ???????)
logging.level.ru.yandex.practicum=DEBUG
logging.level.org.apache.kafka=INFO
logging.level.org.springframework.kafka=INFO