server:
  port: 0

spring:
  application:
    name: warehouse
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.int}

logging:
  level:
    ru.yandex.practicum: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG