# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# ??????
kafka.topic.snapshots=telemetry.snapshots.v1
kafka.topic.hubs=telemetry.hubs.v1

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_home
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ?????????? SQL-??????? ??? ??????
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.jpa.defer-datasource-initialization=true

# gRPC ?????? ??? Hub Router
grpc.client.hub-router.address=static://localhost:59090
grpc.client.hub-router.negotiationType=plaintext

# ???????????
logging.level.ru.yandex.practicum=DEBUG
logging.level.org.apache.kafka=INFO
logging.level.org.springframework.kafka=INFO
logging.level.org.springframework.jdbc.datasource.init=DEBUG

kafka.consumer.snapshot.auto-offset-reset=latest
kafka.consumer.hub.auto-offset-reset=earliest